version: "3.3"
services:
  app:
    build: ./tibber-bot-server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tibber

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tibber
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
